# Generated by Django 4.0.4 on 2022-06-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='advertisement',
            field=models.ImageField(null=True, upload_to='ecommerce/pimg'),
        ),
    ]
