# Generated by Django 4.0.4 on 2022-06-02 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_brand_advertisement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='advertisement',
        ),
    ]
