# Generated by Django 4.0.4 on 2022-06-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_us',
        ),
    ]
